config/routes.rb
Pdf::Application.routes.draw do
  resources :documents

  root :to => "documents#index"

end

app/models/document.rb
class Document < ActiveRecord::Base
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery
end

app/controllers/documents_controller.rb
# highlight: pdf format for show action

class DocumentsController < ApplicationController
  # GET /documents
  # GET /documents.xml
  def index
    @documents = Document.all

    respond_to do |format|
      format.html # index.html.erb
      format.xml  { render :xml => @documents }
    end
  end

  # GET /documents/1
  # GET /documents/1.xml
  def show
    @document = Document.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.xml  { render :xml => @document }
      format.pdf { render :layout => false }
    end
  end

  # GET /documents/new
  # GET /documents/new.xml
  def new
    @document = Document.new

    respond_to do |format|
      format.html # new.html.erb
      format.xml  { render :xml => @document }
    end
  end

  # GET /documents/1/edit
  def edit
    @document = Document.find(params[:id])
  end

  # POST /documents
  # POST /documents.xml
  def create
    @document = Document.new(params[:document])

    respond_to do |format|
      if @document.save
        format.html { redirect_to(@document, :notice => 'Document was successfully created.') }
        format.xml  { render :xml => @document, :status => :created, :location => @document }
      else
        format.html { render :action => "new" }
        format.xml  { render :xml => @document.errors, :status => :unprocessable_entity }
      end
    end
  end

  # PUT /documents/1
  # PUT /documents/1.xml
  def update
    @document = Document.find(params[:id])

    respond_to do |format|
      if @document.update_attributes(params[:document])
        format.html { redirect_to(@document, :notice => 'Document was successfully updated.') }
        format.xml  { head :ok }
      else
        format.html { render :action => "edit" }
        format.xml  { render :xml => @document.errors, :status => :unprocessable_entity }
      end
    end
  end

  # DELETE /documents/1
  # DELETE /documents/1.xml
  def destroy
    @document = Document.find(params[:id])
    @document.destroy

    respond_to do |format|
      format.html { redirect_to(documents_url) }
      format.xml  { head :ok }
    end
  end
end

app/helpers/application_helper.rb
# encoding: utf-8

module ApplicationHelper
  def sanitized_content(content)
    sanitize(content, :tags => %w(p strong em s strike u ul ol li hr))
  end

  def wrap(content, pdf)
    paragraphs = content_to_paragraphs(content)
    while paragraph = paragraphs.shift
      render_paragraph(paragraph, pdf)
    end
  end
  
  private
  
  def render_paragraph(paragraph, pdf)
    pdf.instance_eval do
      if paragraph == "<hr />"
        move_down 5
        pdf.stroke { pdf.horizontal_rule }
        return
      end

      move_down 10

      markup = Nokogiri::HTML(paragraph.gsub(/\s+/, " "))

      mappings = { :em => :i, :strong => :b, :s => :strikethrough, :strike => :strikethrough }
      mappings.keys.each do |key|
        markup.xpath("//#{key}").each do |item|
          item.name = mappings[key].to_s
        end
      end
      
      markup.xpath('//ul/li').each do |item|
        item.replace "BULLET-POINT #{item.text}\n"
      end
      markup.xpath('//ol/li').each_with_index do |item, index|
        item.replace "#{index + 1}. #{item.inner_html}\n"
      end
      
      ['p', 'ol', 'ul'].each do |tag|
        markup.xpath("//#{tag}").each do |t|
          t.replace t.inner_html
        end
      end
      
      paragraph = markup.at_xpath('//body').inner_html.gsub("BULLET-POINT", "•").strip
      text paragraph, :inline_format => true
    end
  end

  def content_to_paragraphs(content)
    regex_string = "<p>.*?</p>|<ul>.*?</ul>|<ol>.*?</ol>|<hr />"
    regex = Regexp.new(regex_string, Regexp::MULTILINE)
    paragraphs = content.scan(regex)
  end
end

app/helpers/documents_helper.rb
module DocumentsHelper
end

app/views/documents/_form.html.erb
<%= form_for(@document) do |f| %>
  <% if @document.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@document.errors.count, "error") %> prohibited this document from being saved:</h2>

      <ul>
      <% @document.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :content %><br />
    <%= f.text_area :content %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/documents/edit.html.erb
<h1>Editing document</h1>

<%= render 'form' %>

<%= link_to 'Show', @document %> |
<%= link_to 'Back', documents_path %>

app/views/documents/index.html.erb
<h1>Listing documents</h1>

<table>
  <tr>
    <th>Content</th>
    <th></th>
    <th></th>
    <th></th>
  </tr>

<% @documents.each do |document| %>
  <tr>
    <td><%= document.content %></td>
    <td><%= link_to 'Show', document %></td>
    <td><%= link_to 'Edit', edit_document_path(document) %></td>
    <td><%= link_to 'Destroy', document, :confirm => 'Are you sure?', :method => :delete %></td>
  </tr>
<% end %>
</table>

<br />

<%= link_to 'New Document', new_document_path %>

app/views/documents/new.html.erb
<h1>New document</h1>

<%= render 'form' %>

<%= link_to 'Back', documents_path %>

app/views/documents/show.html.erb
<!-- highlight: sanitize() -->
<!-- see http://api.rubyonrails.org/classes/ActionView/Helpers/SanitizeHelper.html#method-i-sanitize -->

<p id="notice"><%= notice %></p>

<p>
  <b>Content:</b>
  <%= sanitized_content @document.content %>
</p>

<p>
  [<%= link_to "pdf", document_path(@document, :format => :pdf) %>]
</p>

<%= link_to 'Edit', edit_document_path(@document) %> |
<%= link_to 'Back', documents_path %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Pdf</title>
  <%= stylesheet_link_tag :all %>
  <%= javascript_include_tag :defaults %>
  <%= csrf_meta_tag %>
</head>
<body>

<%= yield %>

</body>
</html>